

export const metadata = {
  title: "Country List App",
  description: "Country List App Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
