"use client";

import Bootstrap from "@/components/Bootstrap";

// export const metadata = {
//   title: "Country List App",
//   description: "Country List App Generated by Next.js",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Bootstrap />
      <body>{children}</body>
    </html>
  );
}
